### ISSUE TITLE
error at annotate peak step

### ISSUE THREAD

**Issue by duncan8659** [Mathelab/ALTRE#53]
I'm trying to do the tutorial workflow and I get this message at the annotate peak step:

Warning: 'ensembldb::SeqnameFilter' is deprecated.
Use 'SeqNameFilter' instead.
See help("Deprecated")
Warning: 'ensembldb::GeneidFilter' is deprecated.
Use 'GeneIdFilter' instead.
See help("Deprecated")
Warning: Error in validObject: invalid class "GeneIdFilter" object: 'like' must be in '==' '!=' 'startsWith' 'endsWith' 'contains'
Stack trace (innermost first):
    126: validObject
    125: initialize
    124: initialize
    123: new
    122: ensembldb::GeneidFilter
    121: is
    120: .processFilterParam
    119: .local
    118: transcripts
    117: transcripts
    116: ensembldb::promoters
    115: ensembldb::promoters
    114: getTSS
    113: eval [/Library/Frameworks/R.framework/Versions/3.4/Resources/library/ALTRE/shinyApp/server.R#57]
    112: eval
    111: withProgress
    110: eventReactiveHandler [/Library/Frameworks/R.framework/Versions/3.4/Resources/library/ALTRE/shinyApp/server.R#52]
     90: combineAnnotateObj
     89: eval
     88: eval
     87: inherits
     86: isTruthy
     85: fun_
     84: dotloop
     83: req
     82: renderDataTable [/Library/Frameworks/R.framework/Versions/3.4/Resources/library/ALTRE/shinyApp/server.R#280]
     81: func
     80: origRenderFunc
     79: output$table3
      2: shiny::runApp
      1: runShinyApp
Warning: Error in validObject: invalid class "GeneIdFilter" object: 'like' must be in '==' '!=' 'startsWith' 'endsWith' 'contains'
Stack trace (innermost first):
    93: <Anonymous>
    92: stop
    91: combineAnnotateObj
    90: eval
    89: eval
    88: inherits
    87: isTruthy
    86: fun_
    85: dotloop
    84: req
    83: plotCombineAnnotatePeaks
    82: renderUI [/Library/Frameworks/R.framework/Versions/3.4/Resources/library/ALTRE/shinyApp/server.R#315]
    81: func
    80: origRenderFunc
    79: output$annotatebarplot
     2: shiny::runApp
     1: runShinyApp
Warning: Error in validObject: invalid class "GeneIdFilter" object: 'like' must be in '==' '!=' 'startsWith' 'endsWith' 'contains'
Stack trace (innermost first):
    86: <Anonymous>
    85: stop
    84: combineAnnotateObj
    83: vbox_fun [/Library/Frameworks/R.framework/Versions/3.4/Resources/library/ALTRE/shinyApp/server.R#420]
    82: shiny::renderUI
    81: func
    80: origRenderFunc
    79: output$statusbox3
     2: shiny::runApp
     1: runShinyApp

since I'm new to this and would LOVE to use it on my own data any help would be great!

**Comment by ewymathe** [comment]
Thank you for reporting this, will look into fixing this shortly and will get back to you once it's done.

**Comment by duncan8659** [comment]
Thanks so much for the quick response!  A colleague suggested that I try the program in an older version of R (I was having the problem with the most recent R for Mac OS 10.11 and higher) and that resolved the error.  I can now get all the way through the workflow to the last step (GREAT analysis) but then it fails.  Not such a problem for my stuff.  I am now however stuck because I need a BED for Drosophila and although I downloaded one from UCSC and formatted it for BED it gives me the following error:

Warning in .Seqinfo.mergexy(x, y) :
  Each of the 2 combined objects has sequence levels not in the other:
  - in 'x': chr2L, chr2R, chr3L, chr3R, chrM, chrY_CP007111v1_random, chrUn_CP007081v1, chrUn_DS483755v1, chrUn_DS484007v1, chrUn_DS484314v1, chrUn_DS484484v1, chrUn_CP007080v1, chrUn_DS484309v1, chrUn_CP007075v1, chrUn_CP007077v1, chrUn_CP007079v1, chrUn_CP007120v1, chrUn_DS483629v1, chrUn_DS483675v1, chrUn_DS483724v1, chrUn_DS483746v1, chrUn_DS483749v1, chrUn_DS483751v1, chrUn_DS483773v1, chrUn_DS483817v1, chrUn_DS483849v1, chrUn_DS483853v1, chrUn_DS483880v1, chrUn_DS483944v1, chrUn_DS483956v1, chrUn_DS484004v1, chrUn_DS484058v1, chrUn_DS484064v1, chrUn_DS484116v1, chrUn_DS484148v1, chrUn_DS484188v1, chrUn_DS484189v1, chrUn_DS484225v1, chrUn_DS484244v1, chrUn_DS484246v1, chrUn_DS484257v1, chrUn_DS484277v1, chrUn_DS484282v1, chrUn_DS484369v1, chrUn_DS484383v1, chrUn_DS484394v1, chrUn_DS484454v1, chrUn_DS484469v1, chrUn_DS484472v1, chrUn_DS484566v1, chrUn_DS484588v1, chrUn_DS484673v1, chrUn_DS484707v1, chrUn_DS484722v [... truncated]
Warning: Error in [[<-: 1522 elements in value to replace 9248 elements
Stack trace (innermost first):
    111: [[<-
    110: [[<-
    109: $<-
    108: $<-
    107: tssannotgrange
    106: combineAnnotatePeaks
    105: eval [/Library/Frameworks/R.framework/Versions/3.3/Resources/library/ALTRE/shinyApp/server.R#59]
    104: eval
    103: withProgress
    102: eventReactiveHandler [/Library/Frameworks/R.framework/Versions/3.3/Resources/library/ALTRE/shinyApp/server.R#52]
     82: combineAnnotateObj
     81: vbox_fun [/Library/Frameworks/R.framework/Versions/3.3/Resources/library/ALTRE/shinyApp/server.R#420]
     80: shiny::renderUI
     79: func
     78: origRenderFunc
     77: output$statusbox3
      2: shiny::runApp
      1: runShinyApp
Warning: Error in [[<-: 1522 elements in value to replace 9248 elements
Stack trace (innermost first):


I’m thinking that perhaps my BED peak files have some unmapped peaks and that these are not in the TSS file?

My BEDs are mapped to dm6

Dianne Duncan
Research Associate
Director, Imaging Core
Biology Department
149 McDonnell Hall
Washington University
St Louis MO 63130
314-935-4764

**Comment by ewymathe** [comment]
Hi Dianne,

The first issue you brought up (error from deprecated function in getTSS()) is now fixed and pushed.
As for this last issue you're raising, yes, it seems to be an annotation issue.  Does the TSS annotation file you have contain all the chromosome types that are in your peak files?

Ewy

**Comment by duncan8659** [comment]
Wow, thanks for being so responsive!  Yes, the latest Drosophila release has lots of unmapped reads so my guess is that they don’t show up in the GTF or BED files from UCSD when you download for refseq genes.  I’m going to try running the program after filtering out those few unmapped peaks from my BED files and see if that works.
Thanks again.
Dianne

Dianne Duncan
Research Associate
Director, Imaging Core
Biology Department
149 McDonnell Hall
Washington University
St Louis MO 63130
314-935-4764

**Comment by ewymathe** [comment]
Sure thing!
OK Dianne, I'm going to close this issue.  Feel free to reach out again if filtering out the unmapped peaks doesn't work.
Ewy

**Comment by duncan8659** [comment]
Hi Ewy
I’ve been trying to use ALTRE today and it wasn’t working for me;  I re-installed it and I still get the same error message:

Installing ALTRE
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/n4/sprgby7d2bd9430f7rs7y6p00000gr/T/Rtmp6R0Hya/devtoolsd0d2acfe68b/Mathelab-ALTRE-e5f07b3'  \
  --library='/Library/Frameworks/R.framework/Versions/3.3/Resources/library' --install-tests

ERROR: dependency ‘AnnotationFilter’ is not available for package ‘ALTRE’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/ALTRE’
Installation failed: Command failed (1)

Not sure what I did.  I’m not familiar enough with R to figure out how to even look for the missing dependency

Great if you could help!

Dianne Duncan
Research Associate
Director, Imaging Core
Biology Department
149 McDonnell Hall
Washington University
St Louis MO 63130
314-935-4764

**Comment by Mathelab** [comment]
Hi Dianne,

Can you try installing the AnnotationFilter package, then installing ALTRE?

source("https://bioconductor.org/biocLite.R")
biocLite("AnnotationFilter")

Ewy

**Comment by duncan8659** [comment]
Will do!

Dianne Duncan
Research Associate
Director, Imaging Core
Biology Department
149 McDonnell Hall
Washington University
St Louis MO 63130
314-935-4764

**Comment by duncan8659** [comment]
Gives this response:

BioC_mirror: https://bioconductor.org
Using Bioconductor 3.4 (BiocInstaller 1.24.0), R 3.3.3 (2017-03-06).
Installing package(s) ‘AnnotationFilter’
Warning message:
package ‘AnnotationFilter’ is not available (for R version 3.3.3)

Dianne Duncan
Research Associate
Director, Imaging Core
Biology Department
149 McDonnell Hall
Washington University
St Louis MO 63130
314-935-4764

**Comment by Mathelab** [comment]
Ah, unfortunately, AnnotationFilter requires R3.4 or greater.  Could you update R?
Ewy

**Comment by duncan8659** [comment]
Yep, thanks!

Dianne Duncan
Research Associate
Director, Imaging Core
Biology Department
149 McDonnell Hall
Washington University
St Louis MO 63130
314-935-4764

**Comment by duncan8659** [comment]
Ok so that got rid of that problem, but now I’m back to this issue that I had early on:

Warning: Error in validObject: invalid class "GeneIdFilter" object: 'like' must be in '==' '!=' 'startsWith' 'endsWith' 'contains'

Which my IT friend told me related to the new Mac R version

Dianne Duncan
Research Associate
Director, Imaging Core
Biology Department
149 McDonnell Hall
Washington University
St Louis MO 63130
314-935-4764

**Comment by Mathelab** [comment]
Did you try to reinstall the package?  That error was fixed and I’m not reproducing it…
Ewy

**Comment by duncan8659** [comment]
Ok Ill try again

Dianne Duncan
Research Associate
Director, Imaging Core
Biology Department
149 McDonnell Hall
Washington University
St Louis MO 63130
314-935-4764

**Comment by Mathelab** [comment]
Just to confirm, this error appears when you run getTSS()?
If it’s still not working, could you share that file with me so I can test?
Ewy

**Comment by duncan8659** [comment]
Ok that did it, thanks so much!

Dianne Duncan
Research Associate
Director, Imaging Core
Biology Department
149 McDonnell Hall
Washington University
St Louis MO 63130
314-935-4764

**Comment by Mathelab** [comment]
Great!
Ewy
